"""Dispatch functions for the 4 pillar tools.

These functions route through the single canonical table,
``open_edit.agent.tools.TOOL_TABLE``: each routing dict maps a pillar
sub-command (query / operation / generate kind) to one of the 26
table entries, so there is exactly one registry of callable tools.
Pillar names themselves (``query_project``, ``edit_project``) are NOT
in the table — they are dispatched by ``kernel.tool_executor``.

``apply_generated_ops`` is a pillar-only composite (commit a list of op
dicts from generate mode); it is not a callable tool, so it lives here
rather than in TOOL_TABLE.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any

from open_edit.agent.tools import TOOL_TABLE

# Sub-command → TOOL_TABLE name for the query (read-only) pillar mode.
_QUERY_ROUTING: dict[str, str] = {
    "list_assets": "list_assets",
    "get_pending_notes": "get_pending_notes",
    "get_style_profile": "get_style_profile",
    "analyze_narrative": "analyze_narrative",
    "search_assets": "search_assets",
    "get_transcript_packed": "get_transcript_packed",
    "get_silence_gaps": "get_silence_gaps",
    "get_timeline_view": "get_timeline_view",
}

# Sub-command → TOOL_TABLE name for the edit pillar mode. Includes the
# 4 re-exported edit tools plus the 7 timeline_ops functions.
_EDIT_ROUTING: dict[str, str] = {
    "add_marker": "add_marker",
    "set_pinned_value": "set_pinned_value",
    "capture_style_hint": "capture_style_hint",
    "import_asset": "import_asset",
    "ingest_local": "ingest_local",
    "add_clip": "add_clip",
    "add_hyperframes_overlay": "add_hyperframes_overlay",
    "trim_clip": "trim_clip",
    "replace_clip_source": "replace_clip_source",
    "change_clip_speed": "change_clip_speed",
    "remove_clip": "remove_clip",
    "set_audio_gain": "set_audio_gain",
    "apply_silence_gaps": "apply_silence_gaps",
    "auto_color_grade": "auto_color_grade",
}

# Generate kind → TOOL_TABLE name for the generate pillar mode.
_GENERATE_ROUTING: dict[str, str] = {
    "sfx": "place_sfx",
    "music": "select_music",
    "visual": "generate_visual_for_segment",
    "silence_cuts": "propose_silence_cuts",
    "remotion": "generate_remotion_composition",
    "init_remotion": "init_remotion_project",
    "write_remotion": "write_remotion_composition",
}


def _with_project_id(params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Attach the graph's stable id to project-scoped pillar calls."""
    p = dict(params) if params else {}
    try:
        from open_edit.storage.edit_graph import EditGraphStore
        from open_edit.storage.paths import ProjectPaths

        db_path = ProjectPaths.for_project(project_path).db_path
        if db_path.exists():
            p["project_id"] = EditGraphStore(db_path).project_id
    except Exception:
        # The wrapped tool returns its normal structured error on failure.
        pass
    return p


def dispatch_query(query: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Dispatch a query to one of the 6 read-only tools."""
    fn = TOOL_TABLE[_QUERY_ROUTING[query]] if query in _QUERY_ROUTING else None
    if fn is None:
        return {"status": "error", "error": f"unknown query: {query!r}"}
    p = _with_project_id(params, project_path)
    return fn(p, str(project_path))


def dispatch_edit(operation: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Dispatch an edit operation to the corresponding tool."""
    if operation == "apply_generated_ops":
        return _apply_generated_ops(dict(params) if params else {}, project_path)
    fn = TOOL_TABLE[_EDIT_ROUTING[operation]] if operation in _EDIT_ROUTING else None
    if fn is None:
        return {"status": "error", "error": f"unknown operation: {operation!r}"}
    p = _with_project_id(params, project_path)
    return fn(p, str(project_path))


def _apply_generated_ops(params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Commit a list of op dicts generated by the generate mode.

    Accepts the shapes the generate tools actually return: full IR op
    model dumps (``kind``-discriminated, e.g. ``AddEffectOp.model_dump()``
    from ``place_sfx`` / ``select_music``, ``AddClipOp.model_dump()`` from
    ``generate_visual_for_segment``). Each op is validated against the
    project's edit graph (reference integrity) and appended atomically.

    The legacy ``{"type": "add_marker", "params": {...}}`` shape is also
    accepted for back-compat.
    """
    add_marker = TOOL_TABLE["add_marker"]

    ops = params.get("ops", [])
    if not isinstance(ops, list):
        return {"status": "error", "error": "apply_generated_ops: ops must be a list"}
    results = []
    for op in ops:
        if not isinstance(op, dict):
            results.append({"status": "error", "error": f"invalid op: {op}"})
            continue
        # Legacy shape {"type": ..., "params": ...} — no producer emits it
        # today, but keep the marker path working for older clients.
        if "type" in op and "kind" not in op:
            op_type = op.get("type", "")
            if op_type == "add_marker":
                results.append(add_marker(op.get("params", {}), str(project_path)))
            else:
                results.append({"status": "error", "error": f"unknown op type: {op_type}"})
            continue
        results.append(_append_ir_op(op, project_path))
    return {"status": "ok", "results": results}


def _append_ir_op(op: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Parse and append one IR op dict (``kind``-discriminated model dump).

    Uses the same vault door as every other mutation
    (``EditGraphStore.append`` → reference validation), so a generated op
    referencing a missing clip/effect is rejected instead of corrupting
    the graph.
    """
    from open_edit.ir.types import OperationUnion
    from open_edit.storage.edit_graph import EditGraphStore
    from open_edit.storage.paths import ProjectPaths
    from pydantic import TypeAdapter

    kind = op.get("kind")
    if not kind:
        return {"status": "error", "error": f"apply_generated_ops: op missing 'kind': {op}"}
    try:
        model = TypeAdapter(OperationUnion).validate_python(op)
    except Exception as exc:
        return {"status": "error", "error": f"apply_generated_ops: invalid {kind} op: {exc}"}
    db = ProjectPaths.for_project(project_path).db_path
    if not db.exists():
        return {"status": "error", "error": "edit graph not found"}
    try:
        sequence_num = EditGraphStore(db).append(model)
    except Exception as exc:
        return {"status": "error", "error": f"apply_generated_ops: {exc}"}
    return {
        "status": "ok",
        "kind": model.kind,
        "edit_id": model.edit_id,
        "sequence_num": sequence_num,
    }


def dispatch_generate(kind: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Generate creative suggestions (SFX, music, visuals, Remotion, silence cuts)."""
    fn = TOOL_TABLE[_GENERATE_ROUTING[kind]] if kind in _GENERATE_ROUTING else None
    if fn is None:
        return {"status": "error", "error": f"unknown generate kind: {kind!r}"}
    p = _with_project_id(dict(params) if params else {}, project_path)
    return fn(p, str(project_path))
