"""Bootstrap codegen: render ``_bootstrap.py`` for in-sandbox execution.

C2 preferred fix (Option A): vendor IR into the bootstrap. The generated
file is self-contained (no ``import open_edit``) and exec'd inside the
sandbox with a custom globals dict.
"""
from __future__ import annotations

import inspect
from typing import Optional

from open_edit.agent.sandbox.staging import _FlushingBuffer
from open_edit.ir.api import IR


def render_bootstrap(
    project_id: str,
    parent_op_id: str,
    originating_note_id: Optional[str] = None,
    ops_file: str = "/scratch/ops.jsonl",
) -> str:
    """Generate _bootstrap.py with the IR class and op models inlined.

    C2 preferred fix (Option A): vendor IR into the bootstrap.
    C1: OPS_FILE defaults to /scratch/ops.jsonl (the in-sandbox mount path
    used by the bwrap backend). The dev backend overrides ``ops_file`` with
    the real host scratch path since it has no /scratch bind mount.
    H10: _FlushingBuffer writes first, then appends.
    """
    from open_edit.ir import types as _types

    ir_source = inspect.getsource(IR)
    # Inline the Operation base class FIRST so subclass references resolve.
    op_types = [
        "Operation",
        "AddClipOp", "RemoveClipOp", "MoveClipOp", "TrimClipOp",
        "AddTransitionOp", "RemoveTransitionOp", "SetTransitionPropertyOp",
        "AddEffectOp", "RemoveEffectOp", "SetEffectParamOp",
        "SetKeyframeOp", "RemoveKeyframeOp",
        "SlipClipOp", "RippleDeleteClipOp", "ChangeClipSpeedOp",
        "SplitClipOp", "ReplaceClipSourceOp", "SetClipSpeedRampOp",
        "SetAudioGainOp", "NormalizeAudioOp",
        "GroupEditsOp", "UngroupEditsOp",
        "RawMltXmlOp", "FreeFormCodeOp",
        "AddHtmlOverlayOp", "RemoveHtmlOverlayOp",
        "AddRemotionCompositionOp", "RemoveRemotionCompositionOp",
    ]
    op_sources = [inspect.getsource(getattr(_types, name)) for name in op_types]
    new_id_source = inspect.getsource(_types.new_id)
    now_iso_source = inspect.getsource(_types.now_iso8601)
    # Single source of truth for the flushing buffer: inline the real class
    # so the generated copy cannot drift from staging._FlushingBuffer.
    flushing_source = inspect.getsource(_FlushingBuffer)

    # Build from a list of lines so all lines start at column 0. (The brief
    # used `textwrap.dedent(f'''...''')` but that's a no-op once the inlined
    # sources (0 indent) are interpolated; the result has 4-space leading
    # whitespace and won't parse.)
    bootstrap_lines = [
        "# === _bootstrap.py (auto-generated by open_edit/agent/sandbox/bootstrap.py) ===",
        "# Self-contained: IR + op models inlined. No import open_edit.",
        "from __future__ import annotations",
        "import json",
        "import uuid",
        "from pathlib import Path",
        "from typing import Annotated, Any, Literal, Optional, Union",
        "from pydantic import BaseModel, Field",
        "from datetime import datetime, timezone",
        "",
        "# --- INLINED: open_edit/ir/ids.py:new_id ---",
        new_id_source,
        "",
        "# --- INLINED: open_edit/ir/ids.py:now_iso8601 ---",
        now_iso_source,
        "",
        "# --- INLINED: op models (Operation base + 12 subclasses) ---",
        *op_sources,
        "",
        "# --- INLINED: open_edit/ir/api.py:IR ---",
        ir_source,
        "",
        "# Write FIRST, then append (H10).",
        "# --- INLINED: open_edit/agent/sandbox/staging.py:_FlushingBuffer ---",
        flushing_source,
        "",
        "# === INJECTED CONSTANTS ===",
        f"PROJECT_ID = {project_id!r}",
        f"PARENT_OP_ID = {parent_op_id!r}",
        f"ORIGINATING_NOTE_ID = {originating_note_id!r}",
        f'OPS_FILE = "{ops_file}"',
        "",
        "_ops = _FlushingBuffer(OPS_FILE)",
        "ir = IR(_ops, project_id=PROJECT_ID, parent_op_id=PARENT_OP_ID, "
        "originating_note_id=ORIGINATING_NOTE_ID)",
        "",
        "# Pydantic rebuild: when the bootstrap is exec'd with a custom globals",
        "# dict (as the Rust binary does), Pydantic's class-not-fully-defined",
        "# check fails for subclasses that use Literal discriminator fields.",
        "# Calling model_rebuild() on each subclass re-evaluates the annotations",
        "# in the right module context and unblocks the validator.",
        *[f"{name}.model_rebuild()" for name in op_types if name != "Operation"],
        "",
    ]
    return "\n".join(bootstrap_lines)
