// Phase 3 Task 7: integration tests for the sandbox binary.
// L7: feature-gated; run with `cargo test --features integration`.

#![cfg(feature = "integration")]

use assert_cmd::Command;
use std::fs;
use tempfile::tempdir;

fn sandbox_bin() -> Command {
    Command::cargo_bin("open-edit-sandbox").unwrap()
}

#[test]
#[ignore = "TODO(Task 6): _bootstrap.py needs the IR module inlined. The actual bootstrap is generated by sandbox_bridge._render_bootstrap() and includes all 24 op class definitions. This ignored test is a placeholder; un-ignoring it requires a Rust-side port of _render_bootstrap or shelling out to a Python helper."]
fn e2e_python_runs_and_writes_ops() {
    let scratch = tempdir().unwrap();
    fs::write(scratch.path().join("code.py"), "ir.add_clip(asset_hash='abc', track_id='t1', position_sec=0.0)").unwrap();
    // TODO(Task 6): the inline bootstrap below references `from open_edit.ir.api import IR`
    // which is not importable inside the sandbox (open_edit is a host-side package,
    // not installed in bwrap's namespace). When un-ignoring this test, replace this
    // body with the output of sandbox_bridge._render_bootstrap() (which inlines all
    // 24 op class definitions via inspect.getsource()).
    fs::write(scratch.path().join("_bootstrap.py"), "import json\nfrom open_edit.ir.api import IR\nclass _Buf(list):\n    def append(self, op):\n        super().append(op)\n        with open('/scratch/ops.jsonl', 'a') as f: f.write(op.model_dump_json() + '\\n')\nir = IR(_Buf(), project_id='p', parent_op_id='e')").unwrap();

    let _ = sandbox_bin()
        .arg("--scratch").arg(scratch.path())
        .arg("--python-bin").arg("/usr/bin/python3.14")
        .arg("--expected-py-version").arg("3.14")
        .arg("--json")
        .assert();
    // The full assert (file existence, op count) is in tests/test_free_form_e2e.py
    // because the Rust binary needs IR/op models inlined into _bootstrap.py.
}

#[test]
fn bwrap_unavailable_reason() {
    // Run with PATH=/nonexistent; bwrap not found → reason=setup_error
    let scratch = tempdir().unwrap();
    sandbox_bin()
        .env("PATH", "/nonexistent")
        .arg("--scratch").arg(scratch.path())
        .arg("--python-bin").arg("/usr/bin/python3.14")
        .arg("--expected-py-version").arg("3.14")
        .arg("--json")
        .assert()
        .failure();
    // Detailed JSON inspection is brittle; the e2e test in Python covers it.
}
