"""Dispatch functions for the 4 pillar tools.

These functions import and call the existing individual tool implementations
from ``open_edit.agent.tools``. They serve as the routing layer between
the new consolidated schemas and the existing backends.
"""
from __future__ import annotations

from pathlib import Path
from typing import Any


def dispatch_query(query: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Dispatch a query to one of the 5 read-only tools."""
    from open_edit.agent.tools import (
        analyze_narrative,
        get_pending_notes,
        get_style_profile,
        list_assets,
        search_assets,
    )

    routing: dict[str, Any] = {
        "list_assets": list_assets,
        "get_pending_notes": get_pending_notes,
        "get_style_profile": get_style_profile,
        "analyze_narrative": analyze_narrative,
        "search_assets": search_assets,
    }
    fn = routing.get(query)
    if fn is None:
        return {"status": "error", "error": f"unknown query: {query!r}"}
    p = dict(params) if params else {}
    return fn(p, str(project_path))


def dispatch_edit(operation: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Dispatch an edit operation to the corresponding tool."""
    from open_edit.agent.tools import (
        add_marker,
        import_asset,
        set_pinned_value,
    )

    p = dict(params) if params else {}
    routing: dict[str, Any] = {
        "add_marker": lambda: add_marker(p, str(project_path)),
        "set_pinned_value": lambda: set_pinned_value(p, str(project_path)),
        "import_asset": lambda: import_asset(p, str(project_path)),
        "apply_generated_ops": lambda: _apply_generated_ops(p, project_path),
    }
    fn = routing.get(operation)
    if fn is None:
        return {"status": "error", "error": f"unknown operation: {operation!r}"}
    return fn()


def _apply_generated_ops(params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Commit a list of op dicts generated by the generate mode."""
    from open_edit.agent.tools import add_marker

    ops = params.get("ops", [])
    if not isinstance(ops, list):
        return {"status": "error", "error": "apply_generated_ops: ops must be a list"}
    results = []
    for op in ops:
        if not isinstance(op, dict):
            results.append({"status": "error", "error": f"invalid op: {op}"})
            continue
        op_type = op.get("type", "")
        if op_type == "add_marker":
            results.append(add_marker(op.get("params", {}), str(project_path)))
        else:
            results.append({"status": "error", "error": f"unknown op type: {op_type}"})
    return {"status": "ok", "results": results}


def dispatch_generate(kind: str, params: dict[str, Any], project_path: Path) -> dict[str, Any]:
    """Generate creative suggestions (SFX, music, visuals, silence cuts)."""
    from open_edit.agent.tools import (
        generate_visual_for_segment,
        place_sfx,
        propose_silence_cuts,
        select_music,
    )

    p = dict(params) if params else {}
    routing: dict[str, Any] = {
        "sfx": lambda: place_sfx(p, str(project_path)),
        "music": lambda: select_music(p, str(project_path)),
        "visual": lambda: generate_visual_for_segment(p, str(project_path)),
        "silence_cuts": lambda: propose_silence_cuts(p, str(project_path)),
    }
    fn = routing.get(kind)
    if fn is None:
        return {"status": "error", "error": f"unknown generate kind: {kind!r}"}
    return fn()
